/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:67f63044-f523-4719-8498-9766810e5c32",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_pR7Lb4bhm",
    "aws_user_pools_web_client_id": "5gmbh8e12c2au4phch8d9k7ovo",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://vxeoxjv2lndhfjmzcee3hzq7xq.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "orderlam",
            "endpoint": "https://l8d0fucnx3.execute-api.ap-southeast-1.amazonaws.com/dev",
            "region": "ap-southeast-1"
        }
    ],
    "aws_user_files_s3_bucket": "ecommerce492af8242daa4010a8d1b894d23288a6101109-dev",
    "aws_user_files_s3_bucket_region": "ap-southeast-1"
};


export default awsmobile;
